//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dismissal_Permission
    {
        public int Dis_Id { get; set; }
        public int Dis_prd { get; set; }
        public Nullable<int> Dis_Warhouse { get; set; }
        public Nullable<int> Dis_PrdQuantity { get; set; }
        public Nullable<int> Dis_Supplier { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warhous Warhous { get; set; }
    }
}
