//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dismissal_Prd
    {
        public int Diss_Prd { get; set; }
        public int Diss_Id { get; set; }
        public Nullable<int> Diss_PrdQ { get; set; }
    
        public virtual Dismissal_Permission Dismissal_Permission { get; set; }
        public virtual Product Product { get; set; }
    }
}
