//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dismissal_Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dismissal_Permission()
        {
            this.Dismissal_Prd = new HashSet<Dismissal_Prd>();
        }
    
        public int Dis_Id { get; set; }
        public System.DateTime Dis_CreaedAt { get; set; }
        public Nullable<int> Dis_Warhouse { get; set; }
        public Nullable<int> Dis_Custmer { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dismissal_Prd> Dismissal_Prd { get; set; }
    }
}
