//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manger
    {
        public int Mng_Id { get; set; }
        public string Mng_Name { get; set; }
        public string Mng_Address { get; set; }
        public string Mng_Email { get; set; }
        public string Mng_Phone { get; set; }
        public Nullable<int> Mng_Warhouse { get; set; }
    
        public virtual Warhous Warhous { get; set; }
    }
}
