//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehousesEntities : DbContext
    {
        public WarehousesEntities()
            : base("name=WarehousesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Dismissal_Permission> Dismissal_Permissions { get; set; }
        public virtual DbSet<Dismissal_Prd> Dismissal_Prd { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Manger> Mangers { get; set; }
        public virtual DbSet<Product_Transfer_Log> Product_Transfer_Log { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supply_Permission> Supply_Permissions { get; set; }
        public virtual DbSet<SupplyPrm_Prds> SupplyPrm_Prds { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warhous> Warhouses { get; set; }
    }
}
