//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Dismissal_Permission = new HashSet<Dismissal_Permission>();
            this.Supply_Permissions = new HashSet<Supply_Permission>();
        }
    
        public int Prd_ID { get; set; }
        public string Prd_Name { get; set; }
        public string Prd_Code { get; set; }
        public string Prd_Unit { get; set; }
        public Nullable<decimal> Prd_Price { get; set; }
        public Nullable<System.DateTime> Prd_ProductionDate { get; set; }
        public Nullable<System.DateTime> Prd_ExpireDate { get; set; }
        public Nullable<int> Prd_Supplier { get; set; }
        public string Prd_Image { get; set; }
        public Nullable<int> Prd_Quantity { get; set; }
        public Nullable<int> Prd_Warhouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dismissal_Permission> Dismissal_Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Permission> Supply_Permissions { get; set; }
    }
}
