//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Transfer_Log
    {
        public int Tr_Id { get; set; }
        public Nullable<int> FromWarhouse { get; set; }
        public Nullable<int> ToWarhouse { get; set; }
        public Nullable<int> Tr_Prd { get; set; }
        public Nullable<int> Tr_Quantity { get; set; }
        public Nullable<System.DateTime> Tr_Date { get; set; }
        public Nullable<int> Tr_Remaining_Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Warhous Warhous { get; set; }
        public virtual Warhous Warhous1 { get; set; }
    }
}
