//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Permission
    {
        public int Spl_Id { get; set; }
        public int Spl_prd { get; set; }
        public Nullable<int> Spl_Warhouse { get; set; }
        public Nullable<System.DateTime> Spl_Date { get; set; }
        public Nullable<int> Spl_PrdQuantity { get; set; }
        public Nullable<int> Spl_Supplier { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warhous Warhous { get; set; }
    }
}
