//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply_Permission()
        {
            this.SupplyPrm_Prds = new HashSet<SupplyPrm_Prds>();
        }
    
        public int Spl_Id { get; set; }
        public Nullable<int> Spl_Warhouse { get; set; }
        public Nullable<int> Spl_Supplier { get; set; }
        public Nullable<System.DateTime> Spl_CreatedAt { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Warhous Warhous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyPrm_Prds> SupplyPrm_Prds { get; set; }
    }
}
