//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_Management_System.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warhous
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warhous()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Wrh_Id { get; set; }
        public string Wrh_Name { get; set; }
        public string Wrh_Address { get; set; }
        public string Wrs_Fax { get; set; }
        public string Wrs_Phone { get; set; }
        public Nullable<int> Wrs_Mng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Manger Manger { get; set; }
    }
}
